# Generated by Django 4.2.11 on 2024-04-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_browse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_image",
            field=models.ImageField(upload_to="book_images", verbose_name="BookImage"),
        ),
    ]
