# Generated by Django 4.2.11 on 2024-08-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_browse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowerFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=200)),
                ('user2', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
