# Generated by Django 4.2.11 on 2024-04-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_browse", "0002_bookphotocomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookphotocomment", old_name="user_id", new_name="comment_user",
        ),
    ]
